name: whale_chat
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.5.4
dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.8
  firebase_core: ^4.4.0
  firebase_auth: ^6.1.4
  cloud_firestore: ^6.1.2
  intl: ^0.20.2
  firebase_messaging: ^16.1.1
  cloud_functions: ^6.0.6
  firebase_storage: ^13.0.6
  image_picker: ^1.2.1
  emoji_picker_flutter: ^4.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0

flutter:

  uses-material-design: true
  assets:
    - assets/images/
    - assets/images/emailVerify.png

  fonts:
    - family: PlayfairDisplay
      fonts:
        - asset: assets/fonts/PlayfairDisplay-VariableFont_wght.ttf
        - asset: assets/fonts/PlayfairDisplay-Italic-VariableFont_wght.ttf
          style: italic